graph TD
subgraph Bloque main
  main1["void loop()"]
  t1["Serial.print(t)"]-->|Esperamos 1s|delay("delay(1000)")
  delay-->t2(t = t+1)
  t2-->main1
  main1-->|imprimo <br> por serial|t1
end
  subgraph Bloque setup
  void("void setup()")-->A
  A-->t
  A["Serial.begin(9600);"]
  t["int t = 0;"]
end
  