graph TB
  %% loop
  subgraph loop    
      loop["void loop()"]
      available{"Serial.available"}
      name1["nombre = Serial.readString()"]
      msn1["Serial.print(''Enviaste'': );"]
      msn2["Serial.println(nombre);"]
      loop ---> available
      available --> |si| name1
      available --> |no| loop
      name1 --> msn1
      msn1 -->msn2
      msn2 ----> loop
end
subgraph variables
    t["String nombre = '' '';"]
end
  %% Setup
  subgraph  setup
      void("void setup()")
      A["Serial.begin(9600);"]
      void-->A
  end


